// STATE-SPACE PARAMETERS HEADER 
// automatically generated by acqtools repository 
//pid model
double	Apid[2][2]	={
 	{9.997232452443184e-01,8.939799775056212e-04},
 	{-8.939799775056767e-04,9.992762552555570e-01}
 	};
double	Bpid[2][1]	={
 	{-2.115395163101972e-02},
 	{-2.113031991256189e-02}
 	};
double	Cpid[1][2]	={
 	{-2.115395163101971e-02,2.113031991256189e-02}
 	};
double	Dpid[1][1]	={
 	{2.498750000312344e-07}
 	};
double	xpid[2] 	={ 	0.0e+00,0.0e+00	};

//pd model
double	Apd[1][1]	={
 	{9.990004997501248e-01}
 	};
double	Bpd[1][1]	={
 	{3.160697311512623e-02}
 	};
double	Cpd[1][1]	={
 	{3.160697311512623e-02}
 	};
double	Dpd[1][1]	={
 	{4.997501249375312e-04}
 	};
double	xpd[1] 	={ 	0.0e+00	};

//LFmath model
double	ALFmath[2][2]	={
 	{8.851178217221278e-01,2.057316573430567e-01},
 	{-2.057316573430565e-01,6.793861643790713e-01}
 	};
double	BLFmath[2][1]	={
 	{-3.743948766149674e-01},
 	{-2.638777697099060e-01}
 	};
double	CLFmath[1][2]	={
 	{-3.743948766149676e-01,2.638777697099060e-01}
 	};
double	DLFmath[1][1]	={
 	{1.978958266381918e-02}
 	};
double	xLFmath[2] 	={ 	0.0e+00,0.0e+00	};

//INVQmath model
double	AINVQmath[2][2]	={
 	{6.796955658517646e-01,2.055771312296928e-01},
 	{-2.055771312296932e-01,8.848084202494336e-01}
 	};
double	BINVQmath[2][1]	={
 	{-1.883421475089737e+02},
 	{-3.258141836933168e+01}
 	};
double	CINVQmath[1][2]	={
 	{1.883421475089739e+02,-3.258141836933166e+01}
 	};
double	DINVQmath[1][1]	={
 	{7.919790982060434e+04}
 	};
double	xINVQmath[2] 	={ 	0.0e+00,0.0e+00	};

// https://github.com/HoriFujimotoLab/AcqTools 
// Thomas Beauduin, HFlab (University of Tokyo) 
