// STATE-SPACE PARAMETERS HEADER 
// automatically generated by acqtools repository 
//pid model
double	Apid[2][2]	={
 	{0,0},
 	{0,0}
 	};
double	Bpid[2][1]	={
 	{-0},
 	{-0}
 	};
double	Cpid[1][2]	={
 	{-0,0}
 	};
double	Dpid[1][1]	={
 	{0}
 	};
double	xpid[2] 	={ 	0,0	};

//pd model
double	Apd[1][1]	={
 	{0}
 	};
double	Bpd[1][1]	={
 	{-0}
 	};
double	Cpd[1][1]	={
 	{0}
 	};
double	Dpd[1][1]	={
 	{0}
 	};
double	xpd[1] 	={ 	0	};

//LFmath model
double	ALFmath[2][2]	={
 	{0,0},
 	{-0,0}
 	};
double	BLFmath[2][1]	={
 	{-0},
 	{-0}
 	};
double	CLFmath[1][2]	={
 	{-0,0}
 	};
double	DLFmath[1][1]	={
 	{0}
 	};
double	xLFmath[2] 	={ 	0,0	};

//INVQmath model
double	AINVQmath[2][2]	={
 	{0,0},
 	{-0,0}
 	};
double	BINVQmath[2][1]	={
 	{-0},
 	{-0}
 	};
double	CINVQmath[1][2]	={
 	{0,-0}
 	};
double	DINVQmath[1][1]	={
 	{0}
 	};
double	xINVQmath[2] 	={ 	0,0	};

// https://github.com/HoriFujimotoLab/AcqTools 
// Thomas Beauduin, HFlab (University of Tokyo) 
